-- Ejecuta este archivo una sola vez en Supabase > SQL Editor.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null check (char_length(name) between 2 and 100),
  phone text not null check (char_length(phone) between 5 and 40),
  email text check (email is null or char_length(email) <= 160),
  city text not null check (char_length(city) between 2 and 100),
  product_type text not null check (char_length(product_type) between 2 and 100),
  budget text check (budget is null or char_length(budget) <= 80),
  message text not null check (char_length(message) between 2 and 2000),
  consent boolean not null default false check (consent is true),
  source text not null default 'website' check (source = 'website'),
  status text not null default 'new' check (status in ('new', 'contacted', 'quoted', 'won', 'lost'))
);

alter table public.leads enable row level security;

revoke all on table public.leads from anon, authenticated;
grant insert on table public.leads to anon;

revoke all on sequence public.leads_id_seq from anon, authenticated;
grant usage on sequence public.leads_id_seq to anon;

drop policy if exists "El sitio puede registrar cotizaciones" on public.leads;
create policy "El sitio puede registrar cotizaciones"
on public.leads
for insert
to anon
with check (
  consent is true
  and source = 'website'
  and status = 'new'
);
