-- Cotizaciones creadas por el configurador 2D de FG TOW.
-- Ejecuta este archivo una sola vez en Supabase > SQL Editor.

create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  quote_number text not null unique check (quote_number ~ '^FGT-[0-9]{8}-[A-F0-9]{6}$'),
  name text not null check (char_length(name) between 2 and 100),
  phone text not null check (char_length(phone) between 7 and 40),
  email text not null check (char_length(email) between 5 and 160),
  city text not null check (char_length(city) between 2 and 100),
  state text not null default 'Nuevo León' check (char_length(state) between 2 and 100),
  notes text check (notes is null or char_length(notes) <= 2000),
  trailer_preset text not null check (char_length(trailer_preset) between 5 and 60),
  trailer_width_cm integer not null check (trailer_width_cm between 150 and 220),
  trailer_length_cm integer not null check (trailer_length_cm between 200 and 900),
  axles smallint not null check (axles in (1, 2, 3)),
  configuration jsonb not null check (jsonb_typeof(configuration) = 'object'),
  subtotal numeric(12,2) not null check (subtotal between 1000 and 1000000),
  iva numeric(12,2) not null default 0 check (iva between 0 and 160000),
  total numeric(12,2) not null check (total = subtotal + iva),
  include_iva boolean not null default false,
  email_to text not null default 'contacto@fgtow.com' check (email_to = 'contacto@fgtow.com'),
  email_sent boolean not null default false,
  email_error text check (email_error is null or char_length(email_error) <= 500),
  consent boolean not null default false check (consent is true),
  source text not null default 'website-2d' check (source = 'website-2d'),
  status text not null default 'new' check (status in ('new', 'email_pending', 'contacted', 'quoted', 'won', 'lost')),
  constraint quotes_email_delivery_state_check check (
    (email_sent is true and status = 'new' and email_error is null)
    or (email_sent is false and status = 'email_pending' and email_error is not null)
    or status in ('contacted', 'quoted', 'won', 'lost')
  )
);

create index if not exists quotes_created_at_idx on public.quotes (created_at desc);
create index if not exists quotes_status_created_at_idx on public.quotes (status, created_at desc);
create index if not exists quotes_email_idx on public.quotes (email);

alter table public.quotes enable row level security;

revoke all on table public.quotes from anon, authenticated;
grant insert on table public.quotes to anon;

revoke all on sequence public.quotes_id_seq from anon, authenticated;
grant usage on sequence public.quotes_id_seq to anon;

drop policy if exists "El cotizador 2D puede registrar propuestas" on public.quotes;
create policy "El cotizador 2D puede registrar propuestas"
on public.quotes
for insert
to anon
with check (
  consent is true
  and source = 'website-2d'
  and email_to = 'contacto@fgtow.com'
  and (
    (email_sent is true and status = 'new' and email_error is null)
    or (email_sent is false and status = 'email_pending' and email_error is not null)
  )
);

comment on table public.quotes is 'Cotizaciones preliminares creadas con el configurador 2D de FG TOW.';

-- Migración: ampliar límites para el configurador de medidas personalizadas (food/cargo).
-- Ejecuta esto una sola vez contra una tabla ya creada (el "create table if not exists" de
-- arriba no vuelve a aplicarse si la tabla ya existe). Los nombres de constraint abajo siguen
-- el nombrado automático de Postgres para CHECK inline sin nombre ("<tabla>_<columna>_check");
-- si esta tabla ya fue alterada antes, verifica los nombres reales primero con:
--   select conname from pg_constraint where conrelid = 'public.quotes'::regclass and contype = 'c';
alter table public.quotes drop constraint if exists quotes_trailer_length_cm_check;
alter table public.quotes add constraint quotes_trailer_length_cm_check check (trailer_length_cm between 200 and 900);

alter table public.quotes drop constraint if exists quotes_axles_check;
alter table public.quotes add constraint quotes_axles_check check (axles in (1, 2, 3));

-- Migración: agregar estado de la república a cotizaciones ya creadas.
alter table public.quotes add column if not exists state text not null default 'Nuevo León';
alter table public.quotes drop constraint if exists quotes_state_check;
alter table public.quotes add constraint quotes_state_check check (char_length(state) between 2 and 100);
